# Generated by Django 5.1.3 on 2024-11-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_generalquestion_quiz_creator_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.generalquestion')),
            ],
        ),
    ]
